### ISSUE TITLE
Change 'Summary' to 'Answer'

### ISSUE THREAD

**Issue by Welding-Torch** [supermemoryai/supermemory#124]
When you ask a question, you expect an "answer". Not a summary. I think we should change this
![image](https://github.com/user-attachments/assets/454ca72e-89e6-4ca7-9309-68104125cf36)
to this
![image](https://github.com/user-attachments/assets/053aacd8-18a9-421a-a84e-e0093816f1f0)

**Comment by Dhravya** [comment]
fixed 31b0c0c

**Comment by Welding-Torch** [comment]
That was fast!
