### ISSUE TITLE
Adding Timeseries

### ISSUE THREAD

**Issue by Welding-Torch** [supermemoryai/supermemory#132]
## New Features

- [ ] 1. Adding Timeseries

Allow users to save the timestamp of when they add a piece of content into Supermemory, like the time a note is saved. Users should be able to ask questions like "What did I save in March?" or "What was I working on in the summer?"

- [x]  2. Adding Recommendations to the Homescreen of Supermemory

## Fixes

- [x] 1. Fixing the rate limiting issue when importing saved tweets from X

**Comment by Dhravya** [comment]
Will work on this after we migrate to pg
