### ISSUE TITLE
Onboarding flow problem with saving supermemory.ai to memory

### ISSUE THREAD

**Issue by bluedinan** [supermemoryai/supermemory#136]
In the onboarding flow in step 3 it suggests adding supermemory.ai to the memory, to then enable the first suggested question "what is supermemory" - when trying to save this URL it gives this error: "Memory creation failed: Failed to save to vector store. Backend returned error: Internal Server Error"

Feel free to reach out to me directly if I can help with any additional info or debugging steps.

**Comment by Dhravya** [comment]
hi! 
Yeah, it looks like our markdowner service failed (it extracts content from websites)

**Comment by SynapseShift** [comment]
Can confirm it's working for me now.  The creation of spaces also wasn't working, but that appears to be working now as well.
