### ISSUE TITLE
onboarding flow is shown on each sign in

### ISSUE THREAD

**Issue by aryasaatvik** [supermemoryai/supermemory#141]
- sign in for the first time
- onboarding flow is shown (expected)
- clear cookies
- sign in with the same account again
- onboarding flow is shown again

my guess is hasOnboarded needs to be a field in the `user` table

**Comment by Dhravya** [comment]
thanks - helpful!

**Comment by aryasaatvik** [comment]
I can work on this

**Comment by Dhravya** [comment]
go ahead!

One more quick fix would probably be to check for number of storedContent maybe? if it's more than 1, don't go through onboarding flow
But i think we should still just put it in the db.
