### ISSUE TITLE
memories show up in space count and search even after being deleted

### ISSUE THREAD

**Issue by aryasaatvik** [supermemoryai/supermemory#142]
Deleting a memory doesn't work as expected

- add a new memory to a space
- wait until it shows up in memories
- search for for something related to the memory 
- newly added memory is shown in results (expected)
- delete memory
- memory is still included in space count (x memories)
- memory is still show in results

**Comment by Welding-Torch** [comment]
Hi!

Memories take a few seconds to delete. Can you try checking again? Delete the memory and wait 5-10 seconds. It should disappear

**Comment by aryasaatvik** [comment]
still an issue. deleted the "onboarding flow" and "cinesthetic" memory + a few others yesterday

https://github.com/user-attachments/assets/94b4f4c8-89e0-4965-875a-a987233fbcb5

**Comment by Dhravya** [comment]
ok yes this is an issue that I noticed long ago but forgot to fix. 
will look into it, pushing a major fix today will include this in the PR

**Comment by CodeTorso** [comment]
> * wait until it shows up in memories

that is also a thing that needs to be removed

**Comment by Dhravya** [comment]
Search fixed, space count thing will be revamped. closing now
