### ISSUE TITLE
feat: delete space

### ISSUE THREAD

**Issue by aryasaatvik** [supermemoryai/supermemory#143]
ISBAT delete a space

**Comment by malisettisamrat** [comment]
Hi @aryasaatvik, can you describe more about the feature?

**Comment by Dhravya** [comment]
this would be in the `/space/id` page, should be an easy first issue, anyone wanna take this quickly?

**Comment by malisettisamrat** [comment]
Hi @Dhravya, Can I take this up?

**Comment by abhishekshah5486** [comment]
Hi @Dhravya , I would like to take up this issue.

**Comment by MaheshtheDev** [comment]
@malisettisamrat , any update on this?
