### ISSUE TITLE
broken link in header breadcrumbs

### ISSUE THREAD

**Issue by aryasaatvik** [supermemoryai/supermemory#148]
- navigate to a space
- the space breadcrumb link in header is not valid

![Screenshot 2024-07-23 at 8 57 35 AM](https://github.com/user-attachments/assets/6170e50b-a002-4f6c-86a2-102b8377fb7b)

**Comment by saiyamdubey** [comment]
Certainly! To help you better, could you please provide the lines that need correcting and elaboration? This will allow me to understand the context and offer specific improvements and explanations.

**Comment by alankritkhatri** [comment]
@aryasaatvik  do you mean this link? https://supermemory.ai/space

**Comment by aryasaatvik** [comment]
> @aryasaatvik do you mean this link? https://supermemory.ai/space

yes

**Comment by Yh010** [comment]
on a side note, can someone explain what is a space? i didnt quite understand how to use it

**Comment by Welding-Torch** [comment]
A space is a collection of memories grouped together by topic

**Comment by Welding-Torch** [comment]
Okay, so it seems the issue is this:
![image](https://github.com/user-attachments/assets/9ef6be45-ecdd-48fb-88e8-4a300e9fb922)

Should be a quick and easy fix, thanks for pointing it out! @aryasaatvik

**Comment by binary-amigo** [comment]
Hello, Can you assign this to me?
