### ISSUE TITLE
After clicking 'Save Page', the 'Add Memory' modal should close automatically

### ISSUE THREAD

**Issue by Welding-Torch** [supermemoryai/supermemory#153]
![image](https://github.com/user-attachments/assets/a98bf083-d413-4fef-b507-fdf996dcad31)

After I click 'Save Page', the modal does not automatically close and I am forced to click the 'X' button to close it. This should not be happening. Ideally, I should paste the link and the modal should close instantly.

**Comment by Dhravya** [comment]
The add promise (loading action when content is saved) prevents the modal from closing

a good temperory fix would be to move that promise out of the modal into the home or the layout or something for now

**Comment by ameeetgaikwad** [comment]
can take this, if someone isn't working on this!

cc: @Dhravya

**Comment by Dhravya** [comment]
@ameeetgaikwad assigned

**Comment by ameeetgaikwad** [comment]
@Dhravya on it!

**Comment by ameeetgaikwad** [comment]
> The add promise (loading action when content is saved) prevents the modal from closing
> 
> a good temperory fix would be to move that promise out of the modal into the home or the layout or something for now

maybe we can trigger all the functionality on `onClick` rather than using `action` via forms?

**Comment by Welding-Torch** [comment]
It's done
