### ISSUE TITLE
Supermemory extension covers the entire webpage making the underlying page unusable

### ISSUE THREAD

**Issue by manan30** [supermemoryai/supermemory#165]
Running into a weird issue with the supermemory extension. This does not happen on all websites but on certain websites, the `supermemory-extension-host` div renders on top of the entire webpage causing the underlying website completely unusable. Unfortunately won't be able to share the website or domain as it is confidential information but just putting out that it is a healthcare website

**Comment by Dhravya** [comment]
What other website does this happen on? Would you like a button that just gets rid of supermemory for that specific page?

**Comment by manan30** [comment]
I haven't come across a lot of websites where this is an issue. I was looking at the code and it looks like that div has a fixed style with a very high z-index value which I believe is causing this issue. Not sure if a change can be made over there or the div styling can be tweaked in some reasonable way that can cover such websites. Currently I have blacklisted sites where this issue is happening but I think a button might be good too as an interim fix

**Comment by Dhravya** [comment]
Looks like a one-time thing, haven't seen anyone else complaining about this (will reopen if this becmoes an issue
