### ISSUE TITLE
Clicking on a memory should open it in a New Tab

### ISSUE THREAD

**Issue by Welding-Torch** [supermemoryai/supermemory#167]
If I click on this, it should not open on the same page as Supermemory (this leads to people navigating away from supmem)
![image](https://github.com/user-attachments/assets/8efe03cd-de7a-4846-ba19-be14ea81af1a)
Instead, clicking on it should open it in a new tab.

**Comment by Dhravya** [comment]
good first issue

Dhravya Shah
https://dhravya.dev

**Comment by dishit7** [comment]
on it

**Comment by rishabhguptareal** [comment]
hey is this issue fixed as of now?

**Comment by Welding-Torch** [comment]
Doesn't seem to be fixed, links are still opening in the same tab

**Comment by rishabhguptareal** [comment]
can you assign this to me

**Comment by rishabhguptareal** [comment]
I think this is solved already kindly check it once and then revert back for further processing

**Comment by rishabhguptareal** [comment]
![Screenshot 2024-07-29 202734](https://github.com/user-attachments/assets/2e8c4287-e64b-4f20-abf1-1a1d490f1290)
target is already blank here so it is opening on new tab kindly check if am touching the right issue or issue is some different

**Comment by Welding-Torch** [comment]
> kindly check if am touching the right issue or issue is some different

You're right, it is fixed
