### ISSUE TITLE
Memories section pages tab CARD UI

### ISSUE THREAD

**Issue by priyansh004** [supermemoryai/supermemory#168]
Serach Queries Ui needs adjustments as you can see in image
![Screenshot from 2024-07-26 11-58-01](https://github.com/user-attachments/assets/bfae6609-261e-4989-b18d-48c74860b7aa)

**Comment by Dhravya** [comment]
good point 💀

**Comment by siddarthpai** [comment]
Hey @Dhravya, can I work on this UI issue

**Comment by Dhravya** [comment]
sure!

**Comment by siddarthpai** [comment]
quite new to the platform, how do i replicate this issue? also, can I work on it without the paid Workers plan?
thanks

**Comment by priyansh004** [comment]
@siddarthpai 
Search something on browser and save that page via extension.

**Comment by siddarthpai** [comment]
thanks! working on it now

**Comment by siddarthpai** [comment]
hey @priyansh004 @Dhravya  , i tried replicating this locally as well as using the hosted extension on the web store, it doesn't seem to save a page, are you facing this as well? did you get the extension from the chrome webstore?

**Comment by priyansh004** [comment]
ohh my bad! just add new memory with long URL than go to my memories>>page.
![Screenshot from 2024-07-26 23-11-41](https://github.com/user-attachments/assets/6b6abd96-cbff-4afd-a3d2-8d27659c4d69)

**Comment by siddarthpai** [comment]
Perfect, thanks. I see the issue

**Comment by priyansh004** [comment]
good work bruh!!!
