### ISSUE TITLE
Promised-based toasters when adding memory

### ISSUE THREAD

**Issue by Dhravya** [supermemoryai/supermemory#170]
Right now, the add memory flow is kinda bad - it just shows multiple toasters with a duration time.

making this promise-based would make a lot of sense! 

Documentation here https://sonner.emilkowal.ski/toast#promise

**Comment by iamsatyajit05** [comment]
hey, dhravya, can you assign this to me?

**Comment by CodeTorso** [comment]
> Right now, the add memory flow is kinda bad - it just shows multiple toasters with a duration time.
> 
> making this promise-based would make a lot of sense!
> 
> Documentation here https://sonner.emilkowal.ski/toast#promise

wait what ? :open_mouth:
