### ISSUE TITLE
Extension not working for Arc Browser

### ISSUE THREAD

**Issue by andrebrito16** [supermemoryai/supermemory#172]
I added extension to Arc but not being able to bookmark anything including tweets or websites.

Also feature to import all twitter bookmarks is not working.

**Comment by exectx** [comment]
yeah im facing this issue too

**Comment by Dhravya** [comment]
I use arc, that's weird. I'll be pushing one more huge change with the extension. Can you guys check if it's still the case please?
Will push a fix very soon

**Comment by andrebrito16** [comment]
@Dhravya I've tested extension again now. The imports from another websites is working as expected. But import tweets and all tweets bookmarks continues without success.

**Comment by Dhravya** [comment]
Got it!

**Comment by andrebrito16** [comment]
Here is a small video about importing tweets using extension. Is not being recognized as tweet but only as a page.


https://github.com/user-attachments/assets/3c7705fb-8667-4094-9ce2-4378fb62f9aa

**Comment by Dhravya** [comment]
This is fixed
