### ISSUE TITLE
Still, The url description text on the memories page overflows.

### ISSUE THREAD

**Issue by rakshitdogra** [supermemoryai/supermemory#176]
The URL link description text on the memories page overflows from the cards. 
It is still occurring despite yesterday's #175 pull

![image](https://github.com/user-attachments/assets/912d8c6d-52b4-4a6e-b0bc-f9659cdcf959)

**Comment by sayakongit** [comment]
Hey @rakshitdogra, let me fix this.

**Comment by Dhravya** [comment]
hi guys, this is fixed but the current deployment is a revert because something else broke in the backend
