### ISSUE TITLE
Tutorial for new users

### ISSUE THREAD

**Issue by Rohan-Hazari** [supermemoryai/supermemory#18]
When I first logged in the only thing I knew was that I can save a webpage and ask question on it but I had no idea of other functions like what does filter do and that purple star thing for bookmark was because of supermemory (lol)

Now that I think its pretty obvious but took me some time for me to figure out
It would be great if we gave the user info about what all the feature at the beginning like a tutorial or maybe a help tab or tool tip explaining what it does

ps: i still dont know what filter does :D

**Comment by wxiuce** [comment]
agree

**Comment by MarcusNeufeldt** [comment]
Also no idea how to add tweets / bookmarks

**Comment by Dhravya** [comment]
Yeah, I totally agree. The UI is not that great and we need some sort of an onboarding UI (I remember seeing something like `tour js` but completely forgot about it. it was an amazing library to give tours of an app for new users)

@boederzeng - to add bookmarks and tweets, You can use the +Add button in the sidebar 
@Rohan-Hazari - Filter is to query in spaces only, so you can find something in a "group" of knowledge

**Comment by irfan-iiitr** [comment]
@Dhravya you must have seen driver.js . It allows to create a tour of the website with less effort.

**Comment by Dhravya** [comment]
cc @CodeTorso @kartikk-k  TODO before launch? 

Let's use https://tourguidejs.com/

**Comment by Welding-Torch** [comment]
The onboarding page has been created! https://supermemory.ai/onboarding

**Comment by CodeTorso** [comment]
now I think using tourguide might have been actuallly better instead on onboarding, since more and more things are going to come to home 

but we should mostly try to make the ui simple enough to understand

**Comment by Dhravya** [comment]
i wanted to use tour guide too but did not

we should do a combination of both. the current one is not bad but again not interactive enough. could be a modal
