### ISSUE TITLE
Do you have public API endpoints?

### ISSUE THREAD

**Issue by pradeepb28** [supermemoryai/supermemory#183]
Do you have public API endpoints where I could send data from other apps to Supermemory as per needed?

The goal is just to send it nothing else. It would be great if you can open an API endpoint that allows us to do this. This endpoint could protect with a Bearer token as an authorization.

**Comment by Dhravya** [comment]
Yes! We do!!! 

POST on `/api/store` with `Authorization: Bearer <your session token>` with this json:

```ts
export const addFromAPIType = z.object({
	pageContent: z.string(),
	url: z.string(),
	type: z.string().default("page"),
	title: z.string().optional().default("Untitled"),
	description: z.string().optional().default(""),
	ogImage: z.string().optional(),
	image: z.string().optional(),
	spaces: z.array(z.string()).optional().default([]),
});
```

**Comment by CodeTorso** [comment]
dhravya any updates on this :smiley:  ? since you were assigned

**Comment by Dhravya** [comment]
I think a good way forward would
be to give everyone an API key they can use to send data. would be interesting & cool!

**Comment by pradeepb28** [comment]
it would be great if there is a way to look at all the public API spec. FYI, I couldn't find link on the website.

**Comment by Dhravya** [comment]
Yeah! This is a docs thing too. stuff is not really properly coordinated right now
