### ISSUE TITLE
Extension for Firefox

### ISSUE THREAD

**Issue by Balaram6712** [supermemoryai/supermemory#188]
Would be a quick enhancement if we can convert the existing extension to firefox add-on for people who prefer using firefox browser.

**Comment by krakenftw** [comment]
I tried converting the already present extension for chrome to firefox but failed. The documentation of extension.js.org for firefox is very limited. I guess we will need to manually change the APIs for browser w.r.t firefox.

**Comment by Dhravya** [comment]
TODO for later after actually making our chrome ratings better xD

**Comment by Kuki77** [comment]
Any chance for a FF addon in the coming weeks?!

**Comment by Akashamba** [comment]
any chance this is coming soon in 2026?
