### ISSUE TITLE
design related issue in landing page & chat (mobile view)

### ISSUE THREAD

**Issue by meetpateltech** [supermemoryai/supermemory#192]
On the landing page, previously there is an issue of overlapping text. After fixing that, there is now a huge unwanted space. Additionally, in some cards, there is a blank space between the image and the content part (as you can see in the attached image).

![InCollage_20240730_185152041](https://github.com/user-attachments/assets/b5e07edf-8129-425c-958e-561b97a18646)

Also, in the chat, if the AI-generated recommendations are too long, they do not display properly (as shown in the attached image).

![Screenshot_20240728-102059~2](https://github.com/user-attachments/assets/8c7c2ed6-b3b3-4346-851b-579e4fe25ac1)

- also, there needs to be a gap between the pro mode and the search space component.

**Comment by Dhravya** [comment]
I just removed pro mode for now, we gotta put more thought into that

**Comment by Dhravya** [comment]
I just removed pro mode for now, we gotta put more thought into that
