### ISSUE TITLE
Running "pnpm run deploy" and getting this SQLite issue

### ISSUE THREAD

**Issue by kellemar** [supermemoryai/supermemory#194]
The migrations are already done but I'm getting this error related to SQLite when trying to run a deploy.

![Screenshot 2024-07-31 at 4 56 50 PM](https://github.com/user-attachments/assets/9a596ac0-f5c2-490d-ad9e-1570b13c5d6e)

Is there something I'm missing?

**Comment by Yh010** [comment]
did you check  the type errors @kellemar ?
