### ISSUE TITLE
Note when deleted should be freed from the RAG

### ISSUE THREAD

**Issue by lotusorrose** [supermemoryai/supermemory#195]
Create a note like 
`I am donald duck.` 
query based on the note/memory
`who am I`
Response is from the note/memory, so far so good.
Delete the note,
rerun the query, it still points to the note/memory which was deleted

**Comment by Dhravya** [comment]
I'm investigating this

**Comment by Dhravya** [comment]
Fixed

**Comment by lotusorrose** [comment]
seems to still exist on https://supermemory.ai

**Comment by lotusorrose** [comment]
![image](https://github.com/user-attachments/assets/e5f6f17c-a58e-4df9-929b-76643ef91fd1)
![image](https://github.com/user-attachments/assets/5ebccb52-deff-47c0-961f-b32aa3e8a3d7)

**Comment by lotusorrose** [comment]
any updates?

**Comment by Dhravya** [comment]
trying to reproduce this, it does seem to work for me

**Comment by Dhravya** [comment]
hmmm ok i think i got it. this will be fixed
