### ISSUE TITLE
Tweets Bookmarked not brining thread information unless bookmarking each tweet (?) 

### ISSUE THREAD

**Issue by tomipardinas** [supermemoryai/supermemory#196]
Not sure if this was intentionally made, but supermemory only brings context from the exact tweet bookmarked even if its a thread ? (Is this correct ?) Having issues when asking for long context threads, simple example here where I only bookmarked the main tweet from a thread which is only 1/10th of the information 

<img width="804" alt="image" src="https://github.com/user-attachments/assets/0fcf78e1-8aa3-4897-9eca-984a8748c875">
<img width="803" alt="image" src="https://github.com/user-attachments/assets/d313396c-f05f-4d02-bc60-ec2d8f1eb1c7">
<img width="557" alt="image" src="https://github.com/user-attachments/assets/4f85b325-2816-4a0d-b80b-d8c1a591f8d4">
<img width="592" alt="image" src="https://github.com/user-attachments/assets/ac11439f-1a95-4779-a761-a61e598faadf">

I usually bookmark only the main tweet, but still want access to the rest of the context from the thread, any ideas on how I could access ?

Best,

Tomas

**Comment by Dhravya** [comment]
@ThakerKush what can we do about this?

**Comment by Dhravya** [comment]
This is expected behaviour tbh, we are going to run a CRON job that updates all tweets -> threads every week. closing for now
