### ISSUE TITLE
[Bug] (?) Unable to use telegram bot, doesn't recognize I've signed in

### ISSUE THREAD

**Issue by dot-Justin** [supermemoryai/supermemory#200]
Title: Frustrating Experience with Supermemory Bot

It gives me a link, so I sign out of SM, click the link, sign back in, and nothing changes in the Telegram chat. If I send any message, it repeats the canned message, "`Welcome to Supermemory bot. I am here to help you...`"

I use Arc browser, but even trying on Chrome yields the same result. Am I doing anything wrong?

**Comment by Dhravya** [comment]
@MaheshtheDev do you know why the bot might have broken?

**Comment by MaheshtheDev** [comment]
@Dhravya , this PR #201 should fix this issue
