### ISSUE TITLE
[Bug] Telegram bot linked, only responds with "Sorry, I am not able to process your request at the moment."

### ISSUE THREAD

**Issue by dot-Justin** [supermemoryai/supermemory#202]
Title.

![image](https://github.com/user-attachments/assets/f2489ffd-6fde-4a6d-b099-63c6ae14c3c2)

**Comment by charanbhatia** [comment]
@dot-Justin I think the api is not working properly. We can work on this by making sure that we have a proper working API key in env file. 
@aryasaatvik Can you assign this issue to me ?

**Comment by Dhravya** [comment]
Fixed
