### ISSUE TITLE
Typo in README.md: "Volia" should be corrected to "Voila"

### ISSUE THREAD

**Issue by abhishekshah5486** [supermemoryai/supermemory#208]
### Description

There's a small typo in the `README.md` file under the "Import Twitter Bookmarks" section. The word "Volia!" should be corrected to "Voila!".

**Current Text:** Volia

**Corrected Text:** : Voila

### Screenshot of the Issue
[
<img width="1032" alt="Screenshot 2024-08-05 at 2 31 49 AM" src="https://github.com/user-attachments/assets/31cc4293-b0c4-4538-89ef-7f7adf18daaa">
](url)

### Steps to Reproduce:
1. Open the `README.md` file.
2. Scroll down to the "Import Twitter Bookmarks" section.
3. Observe the typo "Volia!" in the final step of the instructions.

### Expected Outcome:
The typo should be corrected to "Voila!" for accurate spelling in the `README.md` file.

### Suggested Fix:
Replace "Volia!" with "Voila!" in the relevant section of the `README.md` file.

**Comment by abhishekshah5486** [comment]
I would love to take up this issue.
Please assign it to me.

**Comment by Welding-Torch** [comment]
Done! Thanks
