### ISSUE TITLE
Policy review needed

### ISSUE THREAD

**Issue by TitasDas** [supermemoryai/supermemory#222]
Hi team,
Wanted to give this a spin and ran into the following error - 

> Supermemory.ai’s request does not comply with Google’s ”Use secure browsers” policy. If this app has a website, you can open a web browser and try signing in from there. If you are attempting to access a wireless network, please follow these instructions.
> 
> You can also contact the developer to let them know their app must comply with Google’s ”Use secure browsers” policy.
> 
> Learn more about this error
> 
> If you are a developer of Supermemory.ai, see error details.
> 
> Error 403: disallowed_useragent
> 

Any chance we can review this and integrate or update the permissions. Or is this just me and I should retry with a different browser?

**Comment by Dhravya** [comment]
UGHHH it's like a thing with google auth on some platforms - super weird, a lot of other apps have the same issue. usually happens in sharesheets/integrated browser windows

<img width="777" alt="image" src="https://github.com/user-attachments/assets/414adeda-610f-4b12-aabf-fa66fa29586b">

**Comment by TitasDas** [comment]
@Dhravya Can we reopen this and try to find a potential solution to this?
