### ISSUE TITLE
Change the "Follow us on twitter" to "Follow us on X"

### ISSUE THREAD

**Issue by charanbhatia** [supermemoryai/supermemory#233]
On the homepage, there is a link that redirects to Twitter. The text currently says 'Follow us on Twitter.' Please change it to 'Follow us on X.

![image](https://github.com/user-attachments/assets/9acb78bc-a19c-42c0-99d3-5e2d5b8f5342)

**Comment by charanbhatia** [comment]
i want to work on this issue. Please assign to me.

**Comment by Dhravya** [comment]
It is twitter, not X
