### ISSUE TITLE
can we support edge extension?

### ISSUE THREAD

**Issue by makabakayangyang** [supermemoryai/supermemory#262]

**Comment by virajmalia** [comment]
@makabakayangyang msedge already supports chrome extensions: https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026

**Comment by MaheshtheDev** [comment]
@makabakayangyang , supermemory extension can be installed in edge as well, since it is chromium based
