### ISSUE TITLE
Missing TIPTAP_TOKEN Documentation in .npmrc for Local Setup

### ISSUE THREAD

**Issue by the-vaibhav** [supermemoryai/supermemory#281]
While setting up the project locally, I encountered an issue with the .npmrc file. The setup process expects an environment variable TIPTAP_TOKEN, but this variable is not mentioned or documented in the self-hosting guide.

### The error messages during pnpm install are as follows:
` WARN  Issue while reading "C:\Users\USER\Desktop\Projects\supermemory\.npmrc". Failed to replace env in config: ${TIPTAP_TOKEN} `
` WARN  Issue while reading "C:\Users\USER\Desktop\Projects\supermemory\.npmrc". Failed to replace env in config: ${TIPTAP_TOKEN} `
` ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@tiptap-pro/extension-table-of-contents/-/extension-table-of-contents-2.11.1.tgz: Not Found - 404
`
### Steps to Reproduce:
1. Clone the repository.
2. Run pnpm install or pnpm update.
3. The warnings and errors mentioned above will be displayed.

### Expected Behavior:

- Documentation should provide information on how to set up or obtain the TIPTAP_TOKEN.
- Alternatively, if the token is not required, the .npmrc file should be adjusted.

### Actual Behavior:

- The system fails to recognize the TIPTAP_TOKEN environment variable.
- There is no mention of the token in the self-hosting guide or contribution documentation.
- A 404 error occurs for the Tiptap Pro package.

### Additional Context:

- Windows 10
- pnpm version: 8.11.0

Could the team clarify if the TIPTAP_TOKEN is necessary for local development, and if so, add documentation for it?

**Comment by jiangxiaoyu66** [comment]
I also have the same problem. How can I solve it！

**Comment by boyleryan** [comment]
I was able to resolve this by signing up for a free account with https://tiptap.dev/, creating a project/app and then going to collaboration - settings - and getting the API Secret. I replaced `${TIPTAP_TOKEN}` in .npmrc with the API Secret, and I was then able to successfully run pnpm install.

<img width="1198" alt="2024-09-12_00-08-28" src="https://github.com/user-attachments/assets/aea82546-7447-4a95-ab80-bd6c39fcbc89">

**Comment by MaheshtheDev** [comment]
@the-vaibhav , I think @ipvr9 solution works perfect. And it is being used for our canvas editor. Will Add to Setup Guide as well. Thanks for the suggestion.
