### ISSUE TITLE
Firefox extension problem

### ISSUE THREAD

**Issue by misterxcrypt** [supermemoryai/supermemory#290]
@MaheshtheDev , fyi you have something called extension in your git repo and @Dhravya has mentioned how to load firefox extension on your own in an issue. So I did that and your supermemory extension came in my extension list. It just not doing what it supposed to do. Maybe you can try on your own to do what I did on firefox and let me know if it works for you.
Thank you for your reply man.

_Originally posted by @misterxcrypt in https://github.com/supermemoryai/supermemory/issues/287#issuecomment-2354646444_

**Comment by MaheshtheDev** [comment]
Closing this as Duplicate #287
