### ISSUE TITLE
UI overflow due to extension interference

### ISSUE THREAD

**Issue by Rahulwagh07** [supermemoryai/supermemory#291]
When using  extension, there is a UI overflow issue that causes additional space (as shown in the screenshot)

![image](https://github.com/user-attachments/assets/40fcea18-6c55-421a-b017-5a2488d9fd85)

**Comment by Dhravya** [comment]
@MaheshtheDev is actively working on it

**Comment by swarajbachu** [comment]
true, first I thought it was due to one particular website, then started seeing the pattern, and when I did inspect element I found out

**Comment by MaheshtheDev** [comment]
this is getting fixed with #292
