### ISSUE TITLE
Adding button for human feedback to prioritise/sort search results

### ISSUE THREAD

**Issue by vasnt** [supermemoryai/supermemory#36]
for every search, tool may suggest  one or more results from database. If there are more than 1 results , is there any way for human/user/tool to prioritise results? (some kind of score). 

So that next time, if same search is carried out, results are sorted by its score.

**Comment by Dhravya** [comment]
That's interesting, how could the scoring system work?

**Comment by vasnt** [comment]
it is interesting problem leading to page ranking algorithm or similar fundamentals. So automated(AI based) scoring(kind of confidence score) as well as adding more weightage/score BY human evaluated/ranked data- So final equation will be combination of both.

**Comment by Dhravya** [comment]
Right now, when we do vector search, the search infact *does* give a similarity score. But right now, I was not effectively using that score to do anything - I just started experimenting with telling the LLM the respective scores and then letting it decide which one to give more priority (according to the prompt) and the responses are clearly much much better.

It will ship with all the other updates in the `redesign` branch soon!

**Comment by Dhravya** [comment]
Not planned for now
