### ISSUE TITLE
Please allows Safari iOS users to use it...

### ISSUE THREAD

**Issue by Emasoft** [supermemoryai/supermemory#41]
Please allows Safari iOS users to use it... this is too cool..

**Comment by MaheshtheDev** [comment]
can you share more info on this, what exactly you mean? Supermemory works in safari too

**Comment by Dhravya** [comment]
Does this mean a mobile app? cc @MaheshtheDev @dhanush17-tech, let's start stuff on it soon

**Comment by MaheshtheDev** [comment]
Honestly, i am down for it man. just waiting for your confirmation from the backend though!

**Comment by Emasoft** [comment]
I mean Safari on iOS of course...! Having your 2nd memory on your iPhone always with you!
It can be anything, your choice:
   
1. it can be an official iOS extension for Safari, distributed via the app store
2. it can be a bookmarklet, but few people keep the favorites bar on
3. it can be an App, and you just use the share menu to send things to it
4. it can be a Userscript (GM scripts are getting popular on iOS thanks to Safari extensions like "Stay" or iOS alternative browsers built around user scripts, like Teak. They are still based on Safari but with tons of features integrated via GM scripts (this is my favorite option).
5. It could be a iOS Shortcut that you activate just double tapping the back of your iPhone!

What is important is that the website should have an UI "touch" friendly, so it can be used from an iPhone/iPad.
And since VOICE dictation works well on iPhone, it would be easy to ask things like:

- "Give me the links to all papers I bookmarked about Prompt Engineering"
- “Find me all the Twitter accounts of AI experts I bookmarked”
- "Give me a custom launch page with all my favorite websites about gaming news"
- “Find me the bookmarks I saved about online gradient mesh generators”
- “Find me all the papers I saved about diffusion curves and mesh gradients”
- "Give me a custom launch page with all my favorite websites about gaming walkthroughs and FAQs"
- “Find me all the links I saved to userscripts and GM scripts hosted on github”
- "Give me a custom launch page with all the websites I bookmarked that offer free online image generation via Stable Diffusion".
- "Show me all the latest headlines from all the newsletters I'm subscribed to"
- "Find all the links, articles, papers, ebooks, pdf, etc. I saved about the classical myths of dragons and dragon slayers."
- "Find all the images I bookmarked or saved authored by Gustave Doré"
- “Show me all the links, articles, ebooks, images, etc. I collected about the myth of Perseus and Andromeda.”
- “Find all the images I saved with anime themes and a resolution high enough to be used as wallpapers.”
- “Find me all the images I saved with cool samurai girls from anime or movies”
- "Find all the ebooks/epubs of Xianxia novels I saved in the last 2 years"
- “Get me all I saved and bookmarked about the Kennedy assassination.”
- “Find all the ebooks and PDFs I saved about gothic architecture.”
- "Find all the bookmarks of Chinese web novels websites that I collected and put them on a launch page."
- "Create a launch page with all the best online web translators supporting Chinese/Japanese/Korean to English"
- "Show me all the bookmarks and guides I saved about how to use FFmpeg to convert audio files"
- "Show me a launch page with all my collected Tweets from this month about KPOP and KDRAMAS"
- "Show me a launch page with all the YouTube channels streaming Chinese dramas with English subtitles that I bookmarked, reporting the latest video titles".
- "Check out all the channels of Youtube with epic background instrumental music I'm subscribed to, and list in a launch page all the channels that posted new videos today."
- “Find me all the bookmarks I created to articles and guides to cooking meat and doing barbecue very well.”
- “Create a launch page with the links to all my favorite online comic strips”
- "Get me any link, website, paper, tutorial, or GitHub repo I saved in the past about Blender scripting"
- "Show me the Twitter threads I saved about character animation techniques"
- "Retrieve that Twitter thread about why the VPNs are mostly useless to protect privacy"
- "Find me that article or paper I saved about how to best watering the garden. I don't remember the exact title."
- "Find me that nice online guide on how to write a good plot for a comic I bookmarked once. I don't remember the title."
- "Find me that WebUI add-on for Stable Diffusion that generated comic pages with vignettes from the plot points of a story. I should have bookmarked it not earlier than 2 months ago."
- "Find me the bookmark to that website that lets me rank things in tiers and generate a nice image. I don't remember the name."
- "Give me a launch page with all my favorite cosplay shopping websites"
...etc.

**Comment by MaheshtheDev** [comment]
@Emasoft , most of the features you mentioned can be solved with mobile app. However, VOICE mode is something we can try with mobile app, need @Dhravya input too on this request

**Comment by Dhravya** [comment]
cc @dhanush17-tech

**Comment by Dhravya** [comment]
In the meanwhile, I'm thinking to make an IOS shortcut! 

The only issue I have currently is that it's kinda hard to do authentication while also being extremely privacy focused. need to think

**Comment by Dhravya** [comment]
@MaheshtheDev @dhanush17-tech are working on a mobile app
