### ISSUE TITLE
Mobile View Layout Issues on Landing Page

### ISSUE THREAD

**Issue by meetpateltech** [supermemoryai/supermemory#96]
hello,

I have noticed a few issues with the landing page when viewed on mobile devices:

![supermemory](https://github.com/Dhravya/supermemory/assets/113581962/b40d8a53-11b2-45a5-9c4b-b06a9dffbff6)

- In the use cases section, the images are not properly set for mobile screens.
- Some text is overlapping and not displaying correctly.

**Comment by Dhravya** [comment]
Thanks! This is a good first issue for onboarding new maintainers of the project, anyone want to take this?

**Comment by binlf** [comment]
Tried fixing this but unfortunately couldn't get the app to start. I keep getting a wrangler error:
![WindowsTerminal_fQCCh6Cjoy](https://github.com/Dhravya/supermemory/assets/104459898/f4cb931f-992b-43cc-b30a-07e25f5413f2)

**Comment by malisettisamrat** [comment]
Hi @Dhravya , Can I work on this issue?

**Comment by Dhravya** [comment]
hi @malisettisamrat ! yes PRs welcome!

**Comment by malisettisamrat** [comment]
Hi @Dhravya, opened a PR #122. Thanks !

**Comment by malisettisamrat** [comment]
@Dhravya it also resolved issue #110. You can close that issue!
